# Generated by Django 5.1.7 on 2025-03-25 07:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscenters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='internalnews',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='receptionist',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='enrolled_date',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='internalnews',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='internalnews',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_type',
        ),
        migrations.RemoveField(
            model_name='member',
            name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='certifications',
        ),
        migrations.AddField(
            model_name='appointment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='class',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='class',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='internalnews',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='internalnews',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalnews',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receptionist',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
