# Generated by Django 5.1.7 on 2025-03-27 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportscenters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='internalnews',
            options={'verbose_name': 'Internal News', 'verbose_name_plural': 'Internal News'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'Progress', 'verbose_name_plural': 'Progresses'},
        ),
        migrations.AlterModelOptions(
            name='receptionist',
            options={'verbose_name': 'Receptionist', 'verbose_name_plural': 'Receptionists'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'Trainer', 'verbose_name_plural': 'Trainers'},
        ),
    ]
