# Generated by Django 5.1.7 on 2025-04-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportscenters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='class',
            name='active',
        ),
        migrations.RemoveField(
            model_name='class',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='class',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='internalnews',
            name='active',
        ),
        migrations.RemoveField(
            model_name='internalnews',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='internalnews',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='active',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_date',
        ),
    ]
