# Generated by Django 5.1.7 on 2025-04-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportscenters', '0003_alter_appointment_options_alter_enrollment_options_and_more'),
        ('sportscenters', '0003_alter_trainer_experience_years_and_more'),
    ]

    operations = [
    ]
