# Generated by Django 5.1.7 on 2025-04-13 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscenters', '0004_merge_20250413_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('member_count', models.IntegerField(default=0)),
                ('new_members', models.IntegerField(default=0)),
                ('cancelled_members', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('enrollment_count', models.IntegerField(default=0)),
                ('attendance_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sportscenters.class')),
            ],
        ),
    ]
