# Generated by Django 5.1.6 on 2025-05-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscenters', '0005_member_cancellation_date_member_join_date_statistic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='schedule',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='class',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
