# Generated by Django 5.1.6 on 2025-05-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportscenters', '0006_rename_schedule_class_end_time_class_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('gym_class', 'member')},
        ),
    ]
