# Generated by Django 5.1.6 on 2025-05-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscenters', '0006_rename_schedule_class_end_time_class_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
