# Generated by Django 5.1.6 on 2025-05-27 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscenters', '0007_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Đăng ký', 'verbose_name_plural': 'Các đăng ký'},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='gym_class',
            field=models.ForeignKey(help_text='Lớp học được đăng ký.', on_delete=django.db.models.deletion.CASCADE, to='sportscenters.class', verbose_name='Lớp học'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='member',
            field=models.ForeignKey(help_text='Thành viên đăng ký lớp học.', on_delete=django.db.models.deletion.CASCADE, to='sportscenters.member', verbose_name='Thành viên'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(default='pending', help_text='Trạng thái đăng ký (ví dụ: pending, confirmed).', max_length=10, verbose_name='Trạng thái'),
        ),
    ]
