# Generated by Django 5.1.6 on 2025-05-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportscenters', '0007_member_push_token'),
        ('sportscenters', '0008_alter_enrollment_options_alter_enrollment_gym_class_and_more'),
    ]

    operations = [
    ]
