# Generated by Django 5.1.6 on 2025-05-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscenters', '0009_merge_20250528_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='push_token',
        ),
        migrations.AddField(
            model_name='class',
            name='current_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
